-- Problem 45 (Triangular, pentagonal, and hexagonal)
-- ==================================================
--
-- Triangle, pentagonal, and hexagonal numbers are generated by the following
-- formulae:
--
--     Triangle        T_n=n(n+1)/2         1, 3, 6, 10, 15, ...
--     Pentagonal      P_n=n(3n−1)/2        1, 5, 12, 22, 35, ...
--     Hexagonal       H_n=n(2n−1)          1, 6, 15, 28, 45, ...
--
-- It can be verified that T_285 = P_165 = H_143 = 40755.
--
-- Find the next triangle number that is also pentagonal and hexagonal.

triangle n = n*(n + 1) `div` 2
pentagonal n = n*(3*n - 1) `div` 2
hexagonal n = n*(2*n - 1)

isIntegral :: (RealFrac a) => a -> Bool
isIntegral x = abs (x - fromIntegral (round x)) < 1e-14

-- 3k² - k - 2n = 0
-- k = (1 + sqrt(1+24n))/6
isPentagonal n = isIntegral k && k > 0
    where
        k = (1 + sqrt (fromIntegral (1+24*n))) / 6

-- 2k² - k - n = 0
-- k = (1 + sqrt(1 + 8n))/4
isHexagonal n = isIntegral k && k > 0
    where
        k = (1 + sqrt (fromIntegral (1 + 8*n))) / 4

main = print . head . filter isPentagonal . filter isHexagonal . map triangle $ [286..]
