#include <stdio.h>

/**
 * Euler project
 *   problem 2 -- Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

int main() {
    int sum=0;
    int fib_prev=1, fib_curr=2;

    while (fib_curr < 4000000) {
        if (fib_curr % 2 == 0) {
            sum += fib_curr;
        }
        int next = fib_prev + fib_curr;
        fib_prev = fib_curr;
        fib_curr = next;
    }
    
    printf("Sum of even Fibonacci numbers under four million is %d\n", sum);

    return 0;
}
